# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# Set workdir
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md ./
COPY duckduckgo_mcp ./duckduckgo_mcp

# Install dependencies and package
RUN pip install --no-cache-dir .

# Default command
CMD ["duckduckgo-mcp"]
